### ISSUE TITLE
Bug when the plugin after create the folder and after stop and start the server the plugin don't load and some times the plugin putting up the plugin for the first time in the server don't load

### ISSUE THREAD

**Issue by noieta13** [JoseGamerPT/RealSkywars#1]
I install the plugin and the plugin was correctly loading but after i stop and start the server the plugin don't load, even removing the plugin folder after stop the server, the plugin still don't load and the error is this one.

[Server thread/ERROR]: Error occurred while enabling RealSkywars v6-9-2022 Build 1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
	at josegamerpt.realskywars.sign.SignManager.loadSigns(SignManager.java:38) ~[RealSkywars.jar:?]
	at josegamerpt.realskywars.RealSkywars.onEnable(RealSkywars.java:320) ~[RealSkywars.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1781]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

¿Is this a bug or a error creating the configuration files?

**Comment by joserodpt** [comment]
Hi there! Please check the signs.yml file to see if it contains anything.

**Comment by noieta13** [comment]
The signs.yml its empty. That mean something?

**Comment by joserodpt** [comment]
It should have "Signs:"

**Comment by noieta13** [comment]
![imagen](https://user-images.githubusercontent.com/104702579/191525786-7203c60f-17bc-4eb8-aa22-5e3a0185b2a2.png)

The signs.yml just contain this without anything else i just delete the realskywars folder so the plugin can create a new folder, but its still coming out the error i show you before.

**Comment by joserodpt** [comment]
Try putting in Signs: and see if it does anything different

**Comment by noieta13** [comment]
Still load the same error.

**Comment by joserodpt** [comment]
See if the most recent commit fixed the issue

**Comment by noieta13** [comment]
I don't know what are you mean. Can you tell me what i need to do?

**Comment by noieta13** [comment]
This can sound dumb but. Can you upload a release or a update to the plugin in spigot with this fix version? because i don't know how to download this new version

**Comment by joserodpt** [comment]
Please check if this version works for you
[RealSkywars.zip](https://github.com/JoseGamerPT/RealSkywars/files/9641447/RealSkywars.zip)

**Comment by noieta13** [comment]
It work! Thank you so much
