### ISSUE TITLE
When I created a game world There is some blocks miss in the game world

### ISSUE THREAD

**Issue by Happies123** [JoseGamerPT/RealSkywars#17]
![2024-12-08_13 59 28](https://github.com/user-attachments/assets/861ac572-5b02-4f5a-a047-bdec8dad42a4)
![2024-12-08_13 59 33](https://github.com/user-attachments/assets/4f59a960-c642-4b23-bda6-2db5f76dabfa)
LOGS:
[latest.log](https://github.com/user-attachments/files/18050924/latest.log)
PLZ THIS PLUGIN IS VERY IMPORTANT FOR ME

**Comment by joserodpt** [comment]
This is not a problem from RealSkywars, it seems that some region files for the world got corrupted:
`[13:55:20] [RegionFile I/O Thread #0/ERROR]: Attempting to read chunk data at [18, 4] but got chunk data for [8, 13] instead! Attempting regionfile recalculation for regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/WARN]: Corrupt regionfile header detected! Attempting to re-calculate header offsets for regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
java.lang.Throwable: null
	at net.minecraft.world.level.chunk.storage.RegionFile.recalculateHeader(RegionFile.java:142) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:242) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.read(ChunkStorage.java:186) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at net.minecraft.server.level.ChunkMap.read(ChunkMap.java:592) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at ca.spottedleaf.moonrise.patches.chunk_system.io.datacontroller.ChunkDataController.readData(ChunkDataController.java:48) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at ca.spottedleaf.moonrise.patches.chunk_system.io.RegionFileIOThread$ChunkDataTask.run(RegionFileIOThread.java:1166) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.pollTasks(PrioritisedQueueExecutorThread.java:114) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[purpur-1.21.1.jar:1.21.1-2328-d49ca07]
[13:55:20] [RegionFile I/O Thread #0/WARN]: Backing up regionfile "C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca" to C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca.-2661490479933768514.backup
[13:55:20] [RegionFile I/O Thread #0/WARN]: Backed up the regionfile to C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca.-2661490479933768514.backup
[13:55:20] [RegionFile I/O Thread #0/INFO]: Starting summary of changes for regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (0,12) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (5,0) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (7,7) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (8,13) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (9,1) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (10,8) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (11,11) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (11,13) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (13,6) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Found missing data for local chunk (15,1) in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca
[13:55:20] [RegionFile I/O Thread #0/INFO]: Local chunk (18,4) changed to point to newer data or correct chunk in regionfile C:\Users\Administrator\Desktop\server\SkyWars\sw-solo-1\.\Map2\region\r.0.0.mca`
See more details here: https://github.com/PaperMC/Paper/issues/4758
