### ISSUE TITLE
When I set the Lobby Item Map -1  This error appear when player joining

### ISSUE THREAD

**Issue by Happies123** [JoseGamerPT/RealSkywars#19]
[19:05:55 INFO]: UUID of player WaterFall is 1d99e9a1-c9e0-3775-b571-dba7d80bc0ad
[19:05:56 ERROR]: [RealSkywars] Error while loading player data for WaterFall!
[19:05:56 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index must be between 0 and 40
[19:05:56 WARN]:        at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:75)
[19:05:56 WARN]:        at RealSkywars.jar//joserodpt.realskywars.api.player.RSWPlayerItems.giveSet(RSWPlayerItems.java:41)
[19:05:56 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.managers.LobbyManager.tpToLobby(LobbyManager.java:66)
[19:05:56 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.managers.PlayerManager.loadPlayer(PlayerManager.java:153)
[19:05:56 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:536)
[19:05:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source)
[19:05:56 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[19:05:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:05:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:05:56 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:05:56 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[19:05:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[19:05:56 WARN]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347)
[19:05:56 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173)
[19:05:56 WARN]:        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
[19:05:56 WARN]:        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13)
[19:05:56 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[19:05:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:05:56 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[19:05:56 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[19:05:56 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551)
[19:05:56 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362)
[19:05:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[19:05:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1575)
[19:05:56 INFO]: WaterFall lost connection: An error occurred while loading your RealSkywars player data.
Please try again later and contact an admin.
[19:05:57 INFO]: WaterFall left the game

I dont want the map item in my lobby so i set it -1 but it error

**Comment by neziw** [comment]
Send your configuration

**Comment by Happies123** [comment]
I changed it to -1




Debug-Mode: false
Config:
  Bungeecord:
    Enabled: false
    Kick-Player: true
    Lobby-Server: lobby
  Use-Vault-As-Currency: false
  Invincibility-Seconds: 3
  Auto-Teleport-To-Lobby: true
  Scoreboard-In-Lobby: true
  Enable-Tab-Formatting: true
  Shops:
    Enable-Shop: true
    Enable-Spectator-Shop: true
    Enable-Kit-Shop: true
    Only-Buy-Kits-Per-Match: false
    Enable-Cage-Block-Shop: true
    Enable-Win-Block-Shop: true
    Enable-Bow-Particles-Shop: true
  Right-Click-Player-Info: true
  PlaceholderAPI-In-Scoreboard: false
  Disable-Player-Reset: false
  Disable-Language-Selection: false
  Disable-Lobby-Items: false
  Disable-Map-Starting-Countdown:
    Message: false
    Actionbar: false
  Item-Slots:
    Lobby:
      Profile: 0
      Maps: -1 #This I changed
      Shop: 8

**Comment by joserodpt** [comment]
This will be added to the 1.1 version update of RealSkywars. Thanks for the suggestion!
