### ISSUE TITLE
/rsw create this error appear

### ISSUE THREAD

**Issue by KaptenZee** [JoseGamerPT/RealSkywars#2]
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'rsw create ' in me.mattstudios.mf.base.CommandHandler(realskywars)
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:259) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.tabCompleteCommand(CraftServer.java:2331) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.tabComplete(CraftServer.java:2303) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Purpur-1791]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[purpur-1.19.2.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[purpur-1.19.2.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:952) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1791]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: me/mattstudios/mf/base/components/MfUtil
        at me.mattstudios.mf.base.CompletionHandler.getTypeResult(CompletionHandler.java:114) ~[RealSkywars (1).jar:?]
        at me.mattstudios.mf.base.CommandHandler.tabComplete(CommandHandler.java:417) ~[RealSkywars (1).jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:253) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more
Caused by: java.lang.ClassNotFoundException: me.mattstudios.mf.base.components.MfUtil
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:174) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.mattstudios.mf.base.CompletionHandler.getTypeResult(CompletionHandler.java:114) ~[RealSkywars (1).jar:?]
        at me.mattstudios.mf.base.CommandHandler.tabComplete(CommandHandler.java:417) ~[RealSkywars (1).jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:253) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more

**Comment by neziw** [comment]
Hey. Can you describe how to reproduce this situation? Also it would be nice if you can share /version output.

**Comment by joserodpt** [comment]
Closed due to inactivity.
