### ISSUE TITLE
bug reload bug

### ISSUE THREAD

**Issue by lizheyo77** [JoseGamerPT/RealSkywars#5]
> rsw reload
[18:05:48 WARN]: java.lang.reflect.InvocationTargetException
[18:05:48 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:05:48 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:05:48 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:05:48 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:05:48 WARN]:        at RealSkywars.jar//me.mattstudios.mf.base.CommandHandler.executeCommand(CommandHandler.java:232)
[18:05:48 WARN]:        at RealSkywars.jar//me.mattstudios.mf.base.CommandHandler.execute(CommandHandler.java:218)
[18:05:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[18:05:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1021)
[18:05:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:984)
[18:05:48 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:541)
[18:05:48 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:488)
[18:05:48 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[18:05:48 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[18:05:48 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[18:05:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:05:48 WARN]: Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: RSWRoomStateChangeEvent may only be triggered synchronously.
[18:05:48 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:05:48 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:05:48 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:05:48 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:05:48 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[18:05:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[18:05:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[18:05:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[18:05:48 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[18:05:48 WARN]:        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.managers.GameManager.endGames(GameManager.java:67)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.RealSkywars.reload(RealSkywars.java:192)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.commands.RealSkywarsCMD.reloadcmd(RealSkywarsCMD.java:84)
[18:05:48 WARN]:        ... 15 more
[18:05:48 WARN]: Caused by: java.lang.IllegalStateException: RSWRoomStateChangeEvent may only be triggered synchronously.
[18:05:48 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[18:05:48 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:05:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.api.RSWEventsAPI.callRoomStateChange(RSWEventsAPI.java:25)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.api.game.modes.RSWGame.setState(RSWGame.java:283)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.api.game.modes.RSWGame.commonResetArena(RSWGame.java:716)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.api.game.modes.Solo.resetArena(Solo.java:178)
[18:05:48 WARN]:        at RealSkywars.jar//joserodpt.realskywars.plugin.managers.GameManager.lambda$endGames$2(GameManager.java:69)
[18:05:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[18:05:48 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[18:05:48 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[18:05:48 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[18:05:48 WARN]:        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:05:48 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
>

**Comment by joserodpt** [comment]
That's been fixed on the latest plugin update. Thanks for reporting!
